### ISSUE TITLE
Smart Leaves Resource pack conflicts with My Better Leaves Resource pack

### ISSUE THREAD

**Issue by NaiNonTH** [TeamMidnightDust/CullLeaves#8]
I don't know what happened but seems the smart leaves resource pack didn't do anything wrong to the other better leaves resource pack. But it happened to my pack and I don't know what is wrong with it.

Pic --> https://imgur.com/a/KJmHVUx
My Personal pack link: https://www.mediafire.com/folder/n2apmskuib8bm/My_Pack

**Comment by NaiNonTH** [comment]
Also, It happened only with one model of my leaves resource pack. I tried to fix it But failed.

**Comment by Motschen** [comment]
Seems weird, but the smart leaves pack isn't meant to be used with better leaves packs anyway, since it just replaces the model of the vanilla leaves. You can take a look at the pack [here](https://github.com/TeamMidnightDust/CullLeaves/blob/main/src/main/resources/resourcepacks/smartleaves/assets/minecraft/models/block/leaves.json), it's literally just one single file. Maybe that helps you find out what's wrong with your pack.

**Comment by Motschen** [comment]
Upon further investigation it seems like your pack is broken. There are literally references of a missing texture in the leaves.json file of your pack, I think it'd also have the same issue without the Smart Leaves pack.

**Comment by NaiNonTH** [comment]
> Upon further investigation it seems like your pack is broken. There are literally references of a missing texture in the leaves.json file of your pack, I think it'd also have the same issue without the Smart Leaves pack.

Well, that's weird because it doesn't happen without the Smart Leaves pack.
Anyway, Thank you for your advice :)

**Comment by NaiNonTH** [comment]
Fixed its. Thank you a lot :)
